### ISSUE TITLE
Does not work for Node v6

### ISSUE THREAD

**Issue by roadhump** [node-gh/gh-travis#13]
I run 
```
npm i gh gh-travis -g;
gh
```
And get an error
```
module.js:440
    throw err;
    ^

Error: Cannot find module 'open'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/roadhump/.nvm/versions/node/v6.1.0/bin/gh-travis:19:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

Node version 6.1.0
npm version 3.8.9

**Comment by roadhump** [comment]
Looks like a node bug https://github.com/nodejs/node/issues/6710

**Comment by henvic** [comment]
Thanks.
